Description: >
  This template deploys a Load balancer

Parameters: 
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources: 
  # Elastic Load Balancer
  ELBWebApp:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - Fn::ImportValue: !Sub "${EnvironmentName}-ELB-SG"
      Subnets:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB-SN-1"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB-SN-2"
  # Listener
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: ELBWebApp
      Port: '80'
      Protocol: HTTP
  # Listener Rule
  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
        - Type: forward
          TargetGroupArn: !Ref WebAppTargetGroup
        Conditions:
        - Field: path-pattern
          Values: [/]
        ListenerArn: !Ref Listener
        Priority: 1
  # Target Group
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
Outputs:
  WebAppTargetGroup:
    Description: Web App Target Group
    Value: !Ref WebAppTargetGroup
    Export: 
      Name: !Sub ${EnvironmentName}-WebApp-Target-Group
