Description: >
  This template deploys IAM role for access S3 bucket

Parameters: 
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources: 
  # Define a role for EC2 access to S3 bucket
  RoleForEC2AccessS3:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: EC2InstancePolicyAccessS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'
  # Instance Profile
  ServerInstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: 
        - !Ref RoleForEC2AccessS3
Outputs:
  ServerInstanceProfile:
    Description: Instance profile access S3 bucket
    Value: !Ref ServerInstanceProfile
    Export: 
      Name: !Sub ${EnvironmentName}-InsProFile
  
  RoleForEC2AccessS3:
    Description: Role for access S3 bucket
    Value: !Ref RoleForEC2AccessS3
    Export: 
      Name: !Sub ${EnvironmentName}-S3Role